# Generated by Django 5.0.2 on 2024-04-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confi_certificados',
            name='formato',
        ),
    ]
