# Generated by Django 5.0.2 on 2024-05-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='pin',
            new_name='numero_radicado',
        ),
    ]
