# Generated by Django 5.0.2 on 2024-04-30 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0002_convenio_id_user'),
        ('instancias', '0002_remove_confi_certificados_formato'),
    ]

    operations = [
    ]
