# Generated by Django 5.0.4 on 2024-05-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0002_datos_id_conv'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='usuario_convenio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
