# Generated by Django 5.0.2 on 2024-02-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0002_convenio_imagen_banner_alter_convenio_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
