# Generated by Django 5.0.2 on 2024-02-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0003_alter_convenio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='contraseña_webservice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='id_vigenica',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='usuario_weservice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
