# Generated by Django 4.2.5 on 2024-02-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0004_alter_convenio_contraseña_webservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='id_vigenica',
            field=models.IntegerField(null=True),
        ),
    ]
