# Generated by Django 5.0.2 on 2024-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0004_alter_convenio_contraseña_webservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='contraseña_convenio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='id_vigenica',
            field=models.IntegerField(null=True),
        ),
    ]
