# Generated by Django 5.0.2 on 2024-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0005_convenio_contraseña_convenio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formato_entrega',
            name='pkcs10',
        ),
        migrations.RemoveField(
            model_name='formato_entrega',
            name='token_integer',
        ),
        migrations.RemoveField(
            model_name='formato_entrega',
            name='token_virtual',
        ),
        migrations.RemoveField(
            model_name='tipo_cert',
            name='id_formulario',
        ),
        migrations.AddField(
            model_name='datos',
            name='nuemro_doc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datos',
            name='tipo_doc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
