# Generated by Django 5.0.2 on 2024-03-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0005_alter_convenio_id_vigenica'),
        ('instancias', '0006_remove_formato_entrega_pkcs10_and_more'),
    ]

    operations = [
    ]
