# Generated by Django 4.2.5 on 2024-03-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0005_alter_convenio_id_vigenica'),
        ('instancias', '0006_remove_formato_entrega_pkcs10_and_more'),
    ]

    operations = [
    ]
