# Generated by Django 5.0.2 on 2024-03-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0007_merge_20240315_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='certificados_permi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
