# Generated by Django 5.0.2 on 2024-03-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0008_convenio_certificados_permi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='logueo',
        ),
    ]
