# Generated by Django 4.2.5 on 2024-03-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0008_certificado_convenio_certificados_seleccionados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.AlterField(
            model_name='convenio',
            name='certificados_seleccionados',
            field=models.ManyToManyField(related_name='convenios', to='instancias.tipo_cert'),
        ),
    ]
