# Generated by Django 5.0.2 on 2024-03-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0009_delete_certificado_and_more'),
        ('instancias', '0010_remove_convenio_banner'),
    ]

    operations = [
    ]
