# Generated by Django 5.0.2 on 2024-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instancias', '0013_remove_convenio_operaciones_certificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionFirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VigenciaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='convenio',
            name='certificados_seleccionados',
            field=models.ManyToManyField(related_name='convenios', to='instancias.tipo_cert'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='formatos_entrega',
            field=models.ManyToManyField(related_name='convenios', to='instancias.formatoentrega'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='operaciones_certificado',
            field=models.ManyToManyField(related_name='convenios', to='instancias.operacioncertificado'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='operaciones_firmado',
            field=models.ManyToManyField(related_name='convenios', to='instancias.operacionfirmado'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='operaciones_otp',
            field=models.ManyToManyField(related_name='convenios', to='instancias.operacionotp'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='tipos_certificado',
            field=models.ManyToManyField(related_name='convenios', to='instancias.tipocertificado'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='vigencias_certificado',
            field=models.ManyToManyField(related_name='convenios', to='instancias.vigenciacertificado'),
        ),
    ]
